(() => {
  'use strict';
  const DB='vietnam_class3_recordings_db', STORE='recordings';
  const S={ok:!!(navigator.mediaDevices&&navigator.mediaDevices.getUserMedia&&window.MediaRecorder&&window.indexedDB),st:'idle',mr:null,stream:null,chunks:[],mime:'',startAt:0,elapsed:0,timer:null,rows:[],urls:new Map(),preview:'',err:''};
  const $=(s,r=document)=>r?r.querySelector(s):null;
  const esc=v=>String(v||'').replace(/[&<>"']/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#039;'}[m]));
  const tm=ms=>{let t=Math.max(0,Math.floor((ms||0)/1000));return `${String(Math.floor(t/60)).padStart(2,'0')}:${String(t%60).padStart(2,'0')}`};
  const dt=x=>{let d=new Date(x);return isNaN(d)?'':`${String(d.getMonth()+1).padStart(2,'0')}.${String(d.getDate()).padStart(2,'0')} ${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`};
  function css(){if($('#reading-recorder-style'))return;let e=document.createElement('style');e.id='reading-recorder-style';e.textContent=`.recorder-addon-panel{display:grid;gap:10px;padding-top:18px!important;padding-bottom:18px!important}.rec-top{display:flex;align-items:center;justify-content:space-between}.rec-top h2{margin:0;font-size:1.22rem}.rec-chip{padding:5px 9px;border-radius:999px;background:rgba(93,109,255,.1);color:#5261ee;font-weight:900;font-size:.82rem}.rec-card{display:grid;gap:10px;padding:12px;border-radius:20px;background:linear-gradient(135deg,rgba(93,109,255,.12),rgba(255,255,255,.78));border:1px solid rgba(93,109,255,.14);box-shadow:0 10px 24px rgba(15,23,42,.06)}.rec-main{display:flex;align-items:center;justify-content:space-between}.rec-state{display:flex;align-items:center;gap:8px;font-weight:900}.rec-dot{width:10px;height:10px;border-radius:50%;background:#aab2c8;box-shadow:0 0 0 5px rgba(170,178,200,.12)}.recorder-addon-panel.is-recording .rec-dot{background:#ef4444;box-shadow:0 0 0 5px rgba(239,68,68,.14)}.rec-time{font-size:1.35rem;font-weight:950;font-variant-numeric:tabular-nums}.rec-buttons{display:grid;grid-template-columns:repeat(4,minmax(0,1fr));gap:7px}.rec-buttons button{min-height:38px;border-radius:14px;font-weight:900;padding:8px 6px}.rec-buttons button:disabled{opacity:.38}.rec-buttons .danger,.rec-delete{color:#d93636}.rec-preview{display:grid;gap:6px;padding:9px 10px;border-radius:16px;background:rgba(255,255,255,.86);border:1px solid rgba(93,109,255,.12)}.rec-preview-title{display:flex;justify-content:space-between;color:#5261ee;font-weight:900;font-size:.86rem}.rec-preview audio,.rec-item audio{width:100%;height:40px}.rec-warning{margin:0;padding:9px 11px;border-radius:14px;background:rgba(255,72,72,.08);color:#c53030;font-weight:800;font-size:.88rem}.rec-list-head h3{margin:4px 0 0;font-size:1.04rem}.rec-list{display:grid;gap:9px}.rec-empty{margin:0;padding:12px;border-radius:16px;background:rgba(148,163,184,.08);color:#64748b;font-weight:700;font-size:.9rem}.rec-item{display:grid;gap:8px;padding:10px;border-radius:17px;background:rgba(255,255,255,.78);border:1px solid rgba(15,23,42,.07);box-shadow:0 6px 18px rgba(15,23,42,.05)}.rec-item-title strong{display:block;font-size:.95rem;line-height:1.28;white-space:nowrap;overflow:hidden;text-overflow:ellipsis}.rec-item-title span{display:block;margin-top:2px;color:#73809a;font-size:.78rem;font-weight:800}.rec-text{margin:0;padding:8px 10px;border-radius:12px;background:rgba(93,109,255,.06);font-size:.9rem;line-height:1.42;display:-webkit-box;-webkit-line-clamp:2;-webkit-box-orient:vertical;overflow:hidden}.rec-actions{display:grid;grid-template-columns:1fr 1fr;gap:7px}.rec-download,.rec-delete{min-height:36px;border:0;border-radius:12px;padding:7px 9px;font-weight:900}@media(max-width:430px){.rec-buttons button{font-size:.86rem}.rec-card{padding:11px}}`;document.head.appendChild(e)}
  function db(){return new Promise((ok,no)=>{let r=indexedDB.open(DB,1);r.onupgradeneeded=()=>{let d=r.result;if(!d.objectStoreNames.contains(STORE))d.createObjectStore(STORE,{keyPath:'id'}).createIndex('createdAt','createdAt')};r.onsuccess=()=>ok(r.result);r.onerror=()=>no(r.error)})}
  async function all(){let d=await db();return new Promise((ok,no)=>{let t=d.transaction(STORE,'readonly'),r=t.objectStore(STORE).getAll();r.onsuccess=()=>ok((r.result||[]).sort((a,b)=>new Date(b.createdAt)-new Date(a.createdAt)));r.onerror=()=>no(r.error);t.oncomplete=()=>d.close()})}
  async function put(x){let d=await db();return new Promise((ok,no)=>{let t=d.transaction(STORE,'readwrite');t.objectStore(STORE).put(x);t.oncomplete=()=>{d.close();ok()};t.onerror=()=>{d.close();no(t.error)}})}
  async function del(id){let d=await db();return new Promise((ok,no)=>{let t=d.transaction(STORE,'readwrite');t.objectStore(STORE).delete(id);t.oncomplete=()=>{d.close();ok()};t.onerror=()=>{d.close();no(t.error)}})}
  const pick=()=>['audio/mp4;codecs=mp4a.40.2','audio/mp4','audio/webm;codecs=opus','audio/webm'].find(x=>{try{return MediaRecorder.isTypeSupported(x)}catch{return false}})||'';
  const txt=()=>($('[data-change="ttsInput"]')?.value||'').trim();
  const rowUrl=r=>S.urls.get(r.id)||(S.urls.set(r.id,URL.createObjectURL(r.blob)),S.urls.get(r.id));
  function stopTimer(){if(S.timer)clearInterval(S.timer);S.timer=null} function stopStream(){if(S.stream)S.stream.getTracks().forEach(t=>t.stop());S.stream=null} function tick(){S.elapsed=Date.now()-S.startAt;ui()}
  function clearPrev(){if(S.preview)URL.revokeObjectURL(S.preview);S.preview=''} function makePrev(){clearPrev();if(S.chunks.length)S.preview=URL.createObjectURL(new Blob(S.chunks,{type:S.mime||'audio/webm'}));ui()}
  async function openRec(){S.stream=await navigator.mediaDevices.getUserMedia({audio:{echoCancellation:false,noiseSuppression:false,autoGainControl:false}});if(!S.mime)S.mime=pick();S.mr=S.mime?new MediaRecorder(S.stream,{mimeType:S.mime}):new MediaRecorder(S.stream);S.mr.ondataavailable=e=>{if(e.data&&e.data.size)S.chunks.push(e.data)};S.mr.onerror=()=>{S.err='녹음 중 오류가 발생했습니다.';S.st='idle';stopTimer();stopStream();ui()};S.mr.start(1000)}
  function stopRec(){return new Promise(ok=>{if(!S.mr||S.mr.state==='inactive')return ok();S.mr.ondataavailable=e=>{if(e.data&&e.data.size)S.chunks.push(e.data)};S.mr.onstop=ok;try{S.mr.requestData()}catch{}try{S.mr.stop()}catch{ok()}})}
  async function start(){if(!S.ok||S.st!=='idle')return;try{clearPrev();S.err='';S.chunks=[];S.mime='';S.elapsed=0;S.startAt=Date.now();await openRec();S.st='recording';S.timer=setInterval(tick,300);ui()}catch(e){S.err=e&&e.name==='NotAllowedError'?'마이크 권한이 거부되었습니다.':'녹음을 시작할 수 없습니다.';S.st='idle';stopTimer();stopStream();ui()}}
  async function pause(){if(S.st==='recording'){S.elapsed=Date.now()-S.startAt;S.st='paused';stopTimer();ui();await stopRec();stopStream();S.mr=null;makePrev();return}if(S.st==='paused'){try{clearPrev();S.err='';await openRec();S.startAt=Date.now()-S.elapsed;S.st='recording';S.timer=setInterval(tick,300);ui()}catch{S.err='녹음을 재개할 수 없습니다.';ui()}}}
  async function done(){if(!['recording','paused'].includes(S.st))return;if(S.st==='recording'){S.elapsed=Date.now()-S.startAt;S.st='saving';stopTimer();ui();await stopRec();stopStream();S.mr=null}else{S.st='saving';ui()}let type=S.mime||'audio/webm',createdAt=new Date().toISOString(),text=txt(),ext=type.includes('mp4')?'m4a':'webm';let row={id:`rec_${Date.now()}_${Math.random().toString(16).slice(2)}`,title:text?(text.length>30?`${text.slice(0,30)}…`:text):'읽기 연습 녹음',text,createdAt,durationMs:S.elapsed,mimeType:type,fileName:`vietnam-reading-${createdAt.replace(/[:.]/g,'-').slice(0,19)}.${ext}`,blob:new Blob(S.chunks,{type})};try{await put(row);S.rows=[row,...S.rows];S.err=''}catch{S.err='브라우저 저장공간 문제로 저장하지 못했습니다.'}clearPrev();S.st='idle';S.chunks=[];S.mime='';S.elapsed=0;list();ui()}
  async function cancel(){try{await stopRec()}catch{}clearPrev();stopTimer();stopStream();S.st='idle';S.mr=null;S.chunks=[];S.mime='';S.elapsed=0;S.err='';ui()}
  async function remove(id){if(!confirm('이 녹음을 삭제할까요?'))return;await del(id);let u=S.urls.get(id);if(u)URL.revokeObjectURL(u);S.urls.delete(id);S.rows=S.rows.filter(r=>r.id!==id);list();ui()}
  function download(id){let r=S.rows.find(x=>x.id===id);if(!r)return;let a=document.createElement('a');a.href=rowUrl(r);a.download=r.fileName||'vietnam-reading.webm';document.body.appendChild(a);a.click();a.remove()}
  function listHtml(){if(!S.rows.length)return'<p class="rec-empty">저장된 녹음이 없습니다.</p>';return S.rows.map(r=>`<article class="rec-item"><div class="rec-item-title"><strong>${esc(r.title)}</strong><span>${dt(r.createdAt)} · ${tm(r.durationMs)}</span></div>${r.text?`<p class="rec-text">${esc(r.text)}</p>`:''}<audio controls preload="metadata" src="${rowUrl(r)}"></audio><div class="rec-actions"><button class="rec-download" type="button" data-rec-action="download" data-id="${esc(r.id)}">저장</button><button class="rec-delete" type="button" data-rec-action="delete" data-id="${esc(r.id)}">삭제</button></div></article>`).join('')}
  function list(){let l=$('[data-rec-list]'),c=$('[data-rec-count]');if(l)l.innerHTML=listHtml();if(c)c.textContent=String(S.rows.length)}
  function ui(){let p=$('#reading-recorder-addon');if(!p)return;let r=S.st==='recording',pa=S.st==='paused',sv=S.st==='saving';p.classList.toggle('is-recording',r);$('[data-rec-label]',p).textContent=r?'녹음 중':pa?'일시정지':sv?'저장 중':'대기';$('[data-rec-time]',p).textContent=tm(S.elapsed);$('[data-rec-action="start"]',p).disabled=!S.ok||S.st!=='idle';let pb=$('[data-rec-action="pause"]',p);pb.disabled=!S.ok||(!r&&!pa)||sv;pb.textContent=pa?'재개':'일시정지';$('[data-rec-action="done"]',p).disabled=!S.ok||(!r&&!pa)||sv;$('[data-rec-action="cancel"]',p).disabled=!S.ok||(!r&&!pa)||sv;let pv=$('[data-rec-preview]',p),au=$('[data-rec-preview-audio]',p);if(pv&&au){pv.hidden=!(pa&&S.preview);if(S.preview&&au.src!==S.preview)au.src=S.preview;if(!S.preview)au.removeAttribute('src')}let er=$('[data-rec-error]',p);er.textContent=S.ok?S.err:'이 브라우저에서는 녹음 저장을 지원하지 않습니다.';er.hidden=!er.textContent}
  function mount(){let app=$('#app'),input=$('[data-change="ttsInput"]',app||document);if(!app||!input)return;if($('#reading-recorder-addon')){ui();return}let base=input.closest('.panel')||input.parentElement;if(!base)return;let p=document.createElement('section');p.id='reading-recorder-addon';p.className='panel recorder-addon-panel';p.innerHTML=`<div class="rec-top"><h2>내 발음 녹음</h2><span class="rec-chip"><span data-rec-count>${S.rows.length}</span>개</span></div><div class="rec-card"><div class="rec-main"><div class="rec-state"><span class="rec-dot"></span><span data-rec-label>대기</span></div><strong class="rec-time" data-rec-time>00:00</strong></div><div class="rec-buttons"><button class="primary" type="button" data-rec-action="start">녹음</button><button type="button" data-rec-action="pause" disabled>일시정지</button><button type="button" data-rec-action="done" disabled>완료</button><button class="danger" type="button" data-rec-action="cancel" disabled>취소</button></div><div class="rec-preview" data-rec-preview hidden><div class="rec-preview-title"><span>미리듣기</span><span>마이크 해제됨</span></div><audio controls preload="metadata" data-rec-preview-audio></audio></div><p class="rec-warning" data-rec-error hidden></p></div><div class="rec-list-head"><h3>녹음 목록</h3></div><div class="rec-list" data-rec-list>${listHtml()}</div>`;p.addEventListener('click',e=>{let b=e.target.closest('[data-rec-action]');if(!b)return;let a=b.dataset.recAction,id=b.dataset.id;if(a==='start')start();if(a==='pause')pause();if(a==='done')done();if(a==='cancel')cancel();if(a==='delete'&&id)remove(id);if(a==='download'&&id)download(id)});base.insertAdjacentElement('afterend',p);ui()}
  async function init(){css();try{if(S.ok)S.rows=await all()}catch{S.ok=false}mount();let app=$('#app');if(app)new MutationObserver(()=>mount()).observe(app,{childList:true})}
  document.readyState==='loading'?document.addEventListener('DOMContentLoaded',init):init();
})();